Add GitHub Actions support to publish images
mattermost/mattermost-elasticsearch-docker pull request #4
Opened 2023-06-19 13:00 UTC by isacikgoz

#### Summary
Adds GitHub Actions support to publish `mattermost-elasticsearch` images.

2023-06-20 09:47 UTC, toninis requested changes

2023-06-20 09:47 UTC, toninis commented on .github/workflows/docker.yml
> +    types: [published]
We do not create releases . This should be on [push.tags](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags)

2023-06-20 09:47 UTC, toninis commented on .github/workflows/docker.yml
> +          file: ./Dockerfile
This is needed actually for multi-platform . We can check that 
```suggestion
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
```

2023-06-23 11:15 UTC, isacikgoz commented
Gentle ping @toninis

2023-06-23 11:16 UTC, toninis approved these changes

2023-06-23 11:17 UTC, isacikgoz commented
@toninis so we will need to add `secrets.DOCKERHUB_DEV_USERNAME }}` and `secrets.DOCKERHUB_DEV_TOKEN }}` to this repository right? Or they are accessible organization wide?

2023-06-23 11:18 UTC, toninis commented
> @toninis so we will need to add `secrets.DOCKERHUB_DEV_USERNAME }}` and `secrets.DOCKERHUB_DEV_TOKEN }}` to this repository right? Or they are accessible organization wide?

Already done . You are good to go 🚀

2023-06-23 11:19 UTC, merged